FROM golang:1.16-alpine as build 

RUN apk add --no-cache tzdata
RUN apk --update --no-cache add curl gcc musl-dev
RUN apk add --no-cache ca-certificates git
WORKDIR /go/src/atp/
COPY go.mod .
COPY go.sum .
RUN go mod download 
COPY . .
RUN go build -o app cmd/main.go


FROM frolvlad/alpine-glibc
WORKDIR /app
COPY --from=build /go/src/atp/app  /app/app
COPY tennisATP.db /app/tennisATP.db
EXPOSE 8000 
ENTRYPOINT ["/app/app"]